trigger:
- master

pool:
  vmImage: "macos-latest"

variables:
  buildConfig: "Release" # Can either be "Release" or "Debug"
  solution: "PaintedProsthetics.sln"
stages: 
  - stage: Build
    jobs:
    - job:
      steps: 
        - task: VSBuild@1
          inputs: 
            solution: $(solution)
            configuration: $(buildConfig)
        - script: |
            echo "Building Solution..."
            sudo cd /paintedp/
            sudo dotnet restore $(solution)
            sudo dotnet build -c $(buildConfig) -o $(Build.ArtifactStagingDirectory)/FinishedBuild $(solution)
            echo "Uploading Solution Artifact..."
        # Publish artifacts to Azure
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)/FinishedBuild
            artifactName: FinishedBuild
