trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
  buildConfig: "Release" # Can either be "Release" or "Debug"
  solution: "PaintedProsthetics.sln"
 
stages: 
  - stage: Build
    jobs:
    - job:
      steps: 
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '$(solution)'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '$(solution)'
            arguments: '-o $(Build.ArtifactStagingDirectory)/FinishedBuild -c $(BuildConfig)'
            


        # Publish artifacts to Azure
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)/FinishedBuild
            artifactName: FinishedBuild
